small performance improvement on debug log
pymodbus-dev/pymodbus pull request #1279
Opened 2023-01-23 12:23 UTC by peufeu2

Greetings!

I've been using pymodbus on an Orange Pi Lite, it works great and I'm very pleased with it.

The CPU on this board is very slow, and while profiling I noticed quite a lot of time was spent formatting strings intended to be used in logger.debug()... but unless the log level is actually set to DEBUG, these strings are not used at all, so the cpu time is wasted.

This patch is really simple: I added a bunch of if's to avoid the "slow" (on this CPU) calls to hexlify and other formatting functions unless the logger actually wants the output.

This reduced the cpu usage of the entire application by about 30%, quite spectacular for such a simple patch!

Have a nice day ;)

2023-01-23 12:31 UTC, MAKOMO commented
Instead of changing

```
        txt = f"send: {hexlify_packets(packet)}"
        _logger.debug(txt)
```

into the complex

```
        if _logger.isEnabledFor(logging.DEBUG):
            txt = f"send: {hexlify_packets(packet)}"
            _logger.debug(txt)
```

wouldn't it be more readable to change it into (assuming txt is not used in any other place)?

```
        _logger.debug(f"send: {hexlify_packets(packet)}")
```

The `logger` should automatically avoid to eval its content if no output is to be generated.

2023-01-23 14:15 UTC, peufeu2 commented
> 



> The `logger` should automatically avoid to eval its content if no output is to be generated.

Unfortunately the code inside the logger has no access to local variables from the calling function, so it cannot use them to do the formatting. The f-string you suggest is evaluated from the calling context, then passed to log.debug(), which discards it.

`
>>> def test():
...     print("evaluated")
...     return "e"
...
>>> import logging
>>> logging.debug(f'{test()}')
evaluated
>>>
`

You'd have to pass a deferred evaluation closure, and by this point a simple "if" is simpler. This is how it's usually done in C, but the if() is hidden inside a LOG(level, format, ...) macro.

2023-01-23 14:17 UTC, peufeu2 commented
Now my python modbus server isn't replying to the client talking to it on the serial port. It was working with 3.1.0, it fails with 3.1.1, and it's not because of the logging changes. I'll investigate...

Meanwhile, found a typo:
tcp.py line 213:
`            if self.params.host.startswith("unit:"):`

"unit" should be "unix", since it's about unix sockets...

2023-01-23 15:03 UTC, peufeu2 commented
I found the issue, it works now.

In 3.1.0, StartAsyncSerialServer() calls server.start()
In 3.1.1 it does not and returns the server object.

So I added .start() in my code on the return value of StartAsyncSerialServer(), and now the server serves.

I wonder if this is a bug in my code, perhaps I was supposed to call .start(), but it feels weird that a function called StartAsyncSerialServer() does not actually start the server. Hmm...

2023-01-23 19:24 UTC, janiversen commented
@MAKOMO if you use f strings directly in a logger call, pylint will mark as "bad" code, that is the reason we do not use it. The f string is evaluated before the actual call to _logger.debug, so it works (and I use it frequently for fast testing, but never for production code).

2023-01-23 19:29 UTC, janiversen commented
Just did a fast compare of server/asyncio.py and I cannot see any removal of the .start() call, are you sure you use the newest dev ? (v3.1.1 do not exist).

2023-01-23 19:37 UTC, janiversen requested changes

2023-01-23 19:59 UTC, peufeu2 commented on pymodbus/client/base.py
> +        if _logger.isEnabledFor(logging.DEBUG):
Thanks! However storing the value in a class variable would prevent changes to logging level while the program is running, and that's a really useful feature.

2023-01-23 20:12 UTC, peufeu2 commented
> 

Sorry I got the version number wrong.

To figure out why the server wasn't starting, I was comparing /usr/local/lib/python3.11/site-packages/pymodbus/server/async_io.py which was installed by armbian apt package manager (pymodbus 3.1.0). Here's an extract...

```
async def StartAsyncSerialServer(  # pylint: disable=invalid-name,dangerous-default-value
    context=None,
    identity=None,
    custom_functions=[],
    defer_start=False,
    **kwargs,
):  # pragma: no cover
    """Start and run a serial modbus server.

    :param context: The ModbusServerContext datastore
    :param identity: An optional identify structure
    :param custom_functions: An optional list of custom function classes
        supported by server instance.
    :param defer_start: if set, the server object will be returned ready to start.
            Otherwise, the server will be immediately spun
            up without the ability to shut it off
    :param kwargs: The rest
    """
    server = ModbusSerialServer(
        context, kwargs.pop("framer", ModbusAsciiFramer), identity=identity, **kwargs
    )
    job = _serverList(server, custom_functions, not defer_start)
    if defer_start:
        return server
    await server.start()
    await job.run()
```
`

Note `await server.start()` is there. It's no longer there in the latest version on github, which is why I was surprised my server wasn't starting.

2023-01-24 04:05 UTC, alexrudd2 commented on pymodbus/client/base.py
> +        if _logger.isEnabledFor(logging.DEBUG):
https://github.com/pymodbus-dev/pymodbus/blob/dev/pymodbus/__init__.py

2023-01-24 04:31 UTC, alexrudd2 commented
> To figure out why the server wasn't starting...

Split off into https://github.com/pymodbus-dev/pymodbus/issues/1280

> Meanwhile, found a typo:

https://github.com/pymodbus-dev/pymodbus/pull/1281

2023-01-24 07:34 UTC, janiversen approved these changes
LGTM to me, nice enhancements, thanks.

2023-01-24 07:34 UTC, merged

2023-01-24 09:18 UTC, peufeu2 commented
Have a nice day!