fix no auto reconnect after close/connect in TCPclient
pymodbus-dev/pymodbus pull request #1298
Opened 2023-01-26 08:20 UTC by peufeu2

Greetings,

AsyncModbusTcpClient.close() followed by connect() to reuse the object left it unable to auto-reconnect because delay_ms was set to 0 in close() but not reset to default setting in connect().

Added canceling of auto-reconnect background task in close().

Added check to avoid launching more than one auto-reconnect task in case user calls connect() too many times.

2023-01-26 11:57 UTC, janiversen requested changes

2023-01-26 11:57 UTC, janiversen commented on pymodbus/client/tcp.py
> +    async def _connect( self ):
```suggestion
    async def _connect(self):
```
Please keep our standard

2023-01-26 13:16 UTC, janiversen commented
Please also solve the CI errors.

2023-01-27 07:53 UTC, janiversen commented
delay_ms is not part of the API, but in many of the tests are allowed to use internal values.

Please correct the tests, maybe the tests should simply use the timeout parameter.

2023-01-27 09:12 UTC, peufeu2 commented
Done, looks good!

2023-01-27 10:18 UTC, janiversen approved these changes
LGTM. Thanks

2023-01-27 10:29 UTC, janiversen commented
Seems there are a problem with python 3.11, I have restarted the job to see if it is a real error.

2023-01-27 10:33 UTC, merged