Switch to ruff's version of bandit
pymodbus-dev/pymodbus pull request #1557
Opened 2023-05-30 20:11 UTC by alexrudd2

Ruff has now incorporated basically all Bandit rules we care about.  (The remaining ones pertain to e.g. Django or imports).

Rather than explicitly enabling rules using `bandit.yaml`, I just enabled them all and disabled two useless ones.

Note that ruff uses `Sxxx` to mean Bandit rule `Bxxx`

2023-05-30 20:15 UTC, alexrudd2 commented
Default `bandit` actually flags the following code as violating [`B110`],(https://docs.openstack.org/bandit/1.4.0/plugins/try_except_pass.html):
https://github.com/pymodbus-dev/pymodbus/blob/67d875b785d4f79da7b76413ae62ad71a1259fc3/pymodbus/client/serial_asyncio/__init__.py#L434-L438

Even through `ruff` doesn't find this since it's in a module `__init__()` it should be easy enough to fix, by narrowing the caught Exception.

2023-05-30 20:50 UTC, janiversen requested changes

2023-05-30 20:50 UTC, janiversen commented on pymodbus/server/simulator/http_server.py
> +        http_host: str = "localhost",
That is wrong, local host is 127.0.0.1 whereas 0.0.0.0 allows bind on all interfaces.

2023-05-30 20:51 UTC, janiversen commented
Apart from the wrong change it looks good to me.

2023-05-30 20:56 UTC, alexrudd2 commented
> Or disable bandit for that line, I suppose. I have started rewriting that module so please do what is easiest for you.

I can't (yet) figure out what exceptions are actually thrown, ha.

2023-05-30 21:18 UTC, janiversen commented on pymodbus/server/simulator/http_server.py
> +        http_host: str = "localhost",
Please add The B code, 0.0.0.0 is the standard for listen.

2023-05-31 06:55 UTC, janiversen approved these changes
LGTM. Thanks

2023-05-31 06:55 UTC, merged