Enable RUF013 (implicit optional)
pymodbus-dev/pymodbus pull request #1882
Opened 2023-11-08 19:21 UTC by alexrudd2

The recent PRs eliminating implicit optional are now enough to satisfy `ruff` (although not yet `mypy`)

2023-11-08 20:31 UTC, janiversen requested changes
Seems this PR have a problem, we currently do not have on dev.

2023-11-09 00:13 UTC, alexrudd2 commented
> Seems this PR have a problem, we currently do not have on dev.

Very strange, since there are no code changes.  I think `dev` is broken, but the cache has been hiding it.  

I manually deleted the Linux/3.8 cache and reran the workflow manually, and [it fails](https://github.com/pymodbus-dev/pymodbus/actions/runs/6805365296/job/18505192239).  The tests also fail on my Mac.  I will bisect.

2023-11-09 00:46 UTC, alexrudd2 commented
Triaged as https://github.com/pymodbus-dev/pymodbus/issues/1883

2023-11-09 17:52 UTC, janiversen commented
I just tested dev without cache, no problem on my computer.

2023-11-09 19:11 UTC, alexrudd2 commented
> I just tested dev without cache, no problem on my computer.

(I think you realize this already, but your computer would have broken upon upgrading to `aiohttp==3.9.0b1`)

Anyways, that is solved.   I can't merge until you re-review with approval.

2023-11-09 19:42 UTC, janiversen approved these changes
Thanks

2023-11-09 19:58 UTC, merged