Update transport.py
pymodbus-dev/pymodbus pull request #1889
Opened 2023-11-15 10:15 UTC by garvan2021

transport.abort() is already contains transport.close(), and it would cause error when transport.close() occurs after transport.abort()

2023-11-15 10:25 UTC, garvan2021 commented
Error:
> AttributeError: 'NoneType' object has no attribute 'close'

Machine: ARM 64

How it occurs:
> AsyncModbusSerialClient().async_execute(...)

2023-11-15 11:31 UTC, janiversen requested changes
Looks correct, but it broke all tests so something is not right.

2023-11-15 11:34 UTC, janiversen commented
I think your problem is different, because the error states the self.transport is None !!

2023-11-15 18:37 UTC, alexrudd2 commented
> I think your problem is different, because the error states the self.transport is None !!


If only there were some [type checking tool](https://github.com/pymodbus-dev/pymodbus/pull/1888/files#diff-232ea64eea656684ba1d20bc100847b5fabad3d4627d4b8a51c49041ad84897dR418) that could find such problems with implicit optionals and `None`!
:laughing::laughing:

2023-11-16 16:31 UTC, alexrudd2 commented
> Error:
> 
> > AttributeError: 'NoneType' object has no attribute 'close'
> 
> Machine: ARM 64
> 
> How it occurs:
> 
> > AsyncModbusSerialClient().async_execute(...)

Does this still occur for you if you use the most recent `dev`?

2023-11-18 03:25 UTC, closed without merging

2023-11-18 03:25 UTC, garvan2021 commented
I should be more carefully with my code, may there is another error I missed. So I close the commit temperary and do apologize for my mistake

2023-11-20 00:43 UTC, alexrudd2 commented
> I should be more carefully with my code, may there is another error I missed. So I close the commit temperary and do apologize for my mistake

It was OK.  The test failure only said the code had changed, not that the code was wrong.

I tried to solve your problem a different way. https://github.com/pymodbus-dev/pymodbus/pull/1890.  

Can you try installing from `dev` and seeing if this works for you?