Remove unnecessary abort() call
pymodbus-dev/pymodbus pull request #1890
Opened 2023-11-15 18:56 UTC by alexrudd2

Supercedes #1889

2023-11-15 19:02 UTC, alexrudd2 commented
Ooops, this commit is the wrong one.

2023-11-15 21:46 UTC, janiversen requested changes

2023-11-15 21:46 UTC, janiversen commented on pymodbus/transport/transport.py
> +        """Old alias for closing the connection."""
That is not a "old" ... it is needed because the parent class declares it virtual.

2023-11-15 21:46 UTC, janiversen commented on pymodbus/transport/transport_serial.py
> +        """Old alias for closing the connection."""
Same here.

2023-11-16 07:51 UTC, janiversen approved these changes
Thanks

2023-11-16 07:51 UTC, merged