call async datastore from execute
pymodbus-dev/pymodbus pull request #2144
Opened 2024-04-02 11:32 UTC by ilkka-ollakka

Take into use of async_getValues and async_setValues in modbus-server message handling, allowing datastore (mainly remote datastore) to use async flow.

Split from https://github.com/pymodbus-dev/pymodbus/pull/2127

Depends on https://github.com/pymodbus-dev/pymodbus/pull/2142 and https://github.com/pymodbus-dev/pymodbus/pull/2143

This could be merged also with PR https://github.com/pymodbus-dev/pymodbus/pull/2142 if preferred

2024-04-05 17:29 UTC, janiversen commented
A PR is independent, we do not merge/split PRs. 

If a PR is depending on other PRs then please mark it as draft, so nobody wastes time.

2024-04-09 15:54 UTC, janiversen commented
I have lost the overview...you have 3 open PR`s, is any of them ready to be merged (all comments resolved) ??

Seems you do not allow maintainers to update the PR, so I cannot rebase the 3 PRs, please do a rebase on the one where you want a final review.

2024-04-09 19:12 UTC, ilkka-ollakka commented
> I have lost the overview...you have 3 open PR`s, is any of them ready to be merged (all comments resolved) ??

This one is only one that depends on those 2 other PR's, to my understanding all comments have been reacted.
 
> Seems you do not allow maintainers to update the PR, so I cannot rebase the 3 PRs, please do a rebase on the one where you want a final review.

All are now rebased

2024-04-23 07:53 UTC, janiversen commented
Is this ready for review ?

2024-04-23 08:00 UTC, janiversen requested changes
It might be that remote returns a value in setValues, but we do not expect a value !

Apart from that the code is currently flawed, because not all getValues() calls check for ExceptionResponse, but this is outside this PR.

2024-04-23 08:17 UTC, ilkka-ollakka commented on pymodbus/pdu/bit_write_message.py
> +        result = await context.async_setValues(
fixed

2024-04-23 08:17 UTC, ilkka-ollakka commented on pymodbus/pdu/register_read_message.py
> +        result = await context.async_setValues(
fixed

2024-04-23 08:17 UTC, ilkka-ollakka commented on pymodbus/pdu/register_write_message.py
> +        result = await context.async_setValues(
fixed

2024-04-23 08:18 UTC, ilkka-ollakka commented on pymodbus/pdu/register_write_message.py
> +        result = await context.async_setValues(
fixed

2024-04-23 08:18 UTC, ilkka-ollakka commented on pymodbus/pdu/register_write_message.py
> +        result = await context.async_setValues(
fixed

2024-04-23 08:32 UTC, merged