Add socket arg to AsyncModbusTcpClient
pymodbus-dev/pymodbus pull request #2282
Opened 2024-08-04 15:10 UTC by dsblendo

@janiversen Let me know if this is a reasonable request. I would like to pass an already created socket directly into `AsyncModbusTcpClient`, to pass it directly into `loop.create_connection()`.

2024-08-04 15:20 UTC, janiversen requested changes
I have to think more about this change, for a couple of reasons:
- how to handle reconnect (could reconnect to another server)
- how to interpret host/port parameters, socket comes connected
- How to handle the server (transport is shared)
- this needs new tests cases in transport to ensure there are no side effects.

With the questions properly solved I do not objections.

2024-08-04 15:20 UTC, janiversen commented on pymodbus/transport/transport.py
> +    socket: socket.socket | None = None
This worries me quite a bit, because comm_params was easy printable parameters.

2024-08-04 15:20 UTC, janiversen commented on pymodbus/transport/transport.py
> +                sock=self.comm_params.socket,
This affects both the server (listen) and client (connect), but you have not changed the server part.

This really needs to be tested, what happens if you pass none.

2024-08-05 17:29 UTC, dsblendo commented
@janiversen thanks for the feedback. I will review the lift required to make these changes and meet your requirements to see if it is worthwhile.

2024-09-30 02:39 UTC, closed without merging