Convert endianness
pymodbus-dev/pymodbus pull request #2506
Opened 2024-12-17 10:26 UTC by daanwtb

2024-12-17 10:57 UTC, janiversen requested changes
Please read the standard:

'''
4.2 Data Encoding
 MODBUS uses a ‘big-Endian’ representation for addresses and data items. This means
that when a numerical quantity larger than a single byte is transmitted, the most significant
byte is sent first. So for example
Register size value
16 - bits 0x1234 the first byte sent is 0x12 then 0x34
'''

Your pull request would make sense, for int32 etc.

2024-12-17 10:57 UTC, janiversen commented on pymodbus/client/mixin.py
> +        :param endian: endianness of the byte order
This is wrong, byte order is always big.

What is not defined by the standard is the word order.

2024-12-17 10:57 UTC, janiversen commented on pymodbus/client/mixin.py
> +            byte_list.extend(int.to_bytes(x, 2, endian))
this is wrong, a register is always "big".

2024-12-17 10:57 UTC, janiversen commented on pymodbus/client/mixin.py
> +        cls, value: int | float | str | list[bool], data_type: DATATYPE, endian: Literal["big", "little"] = "big"
see above.

2024-12-17 10:57 UTC, janiversen commented on pymodbus/client/mixin.py
> +        :param endian: endianness to encode bytes to
see above.

2024-12-17 10:57 UTC, janiversen commented on pymodbus/client/mixin.py
> +            int.from_bytes(byte_list[x : x + 2], endian)
see above.

2024-12-17 15:55 UTC, daanwtb commented
You are right about the modbus protocol stating each register should be big-endian, but we have encountered situations where it was not. I like the new implementation convert_from_registers/convert_to_registers but we can only use it if we can also use little endian byte_order. Proposing a new solution and like to hear your opinion.

2024-12-17 16:21 UTC, janiversen commented
Pymodbus implemented the modbus standard NOT all the non-standard implementations!

If you want a different byte order then please convert the bytes in the app.

2024-12-17 16:30 UTC, janiversen requested changes
You miss test cases that shows these conversions actually works.

2024-12-17 16:30 UTC, janiversen commented on pymodbus/client/mixin.py
> +        :param byte_order: Literal[big, small] order of to bytes in 16 bit register encoding (ALMOST always big)
Byte order is fixed by the standard.

2024-12-17 16:30 UTC, janiversen commented on pymodbus/client/mixin.py
> +            byte_list = byte_list[::-1]
This does not convert the order of all registers.

2024-12-18 17:43 UTC, janiversen approved these changes

2024-12-18 17:45 UTC, merged